FROM ocaml/opam:alpine
WORKDIR ezpostgresql
ADD ezpostgresql.opam .
RUN opam pin add -yn ezpostgresql . && \
    opam depext ezpostgresql && \
    opam install --deps-only ezpostgresql
RUN opam install alcotest alcotest-lwt
ADD . .
RUN sudo chown -R opam:nogroup .
CMD opam config exec make test
